CREATE DATABASE FOOD_DELIVERY_BUSINESS;

-- Use the database (important in MySQL / SQL Server)
USE FOOD_DELIVERY_BUSINESS;

CREATE TABLE FOOD_CUSTOMERS(
    CUSTOMER_ID INT NOT NULL,
    CUSTOMER_NAME TEXT NOT NULL,
    CITY TEXT NOT NULL,
    SIGNUP_DATE DATE NOT NULL,
    PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE FOOD_DELIVERY_PARTNERS(
    PARTNER_ID INT NOT NULL,
    PARTNER_NAME TEXT NOT NULL,
    CITY TEXT NOT NULL,
    JOINING_DATE DATE NOT NULL,
    PRIMARY KEY (PARTNER_ID)
);

CREATE TABLE FOOD_RESTAURANTS(
    RESTAURANT_ID INT NOT NULL,
    RESTAURANT_NAME TEXT NOT NULL,
    CITY TEXT NOT NULL,
    CUISINE_TYPE TEXT NOT NULL,
    PRIMARY KEY (RESTAURANT_ID)
);

CREATE TABLE FOOD_ORDERS(
    ORDER_ID INT NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    RESTAURANT_ID INT NOT NULL,
    PARTNER_ID INT NOT NULL,
    ORDER_DATE DATE NOT NULL,
    ORDER_AMOUNT DECIMAL(10,2) NOT NULL,
    DELIVERY_TIME_MINUTES INT NOT NULL,
    ORDER_STATUS TEXT NOT NULL,
    PRIMARY KEY (ORDER_ID),

    FOREIGN KEY (CUSTOMER_ID) REFERENCES FOOD_CUSTOMERS(CUSTOMER_ID),
    FOREIGN KEY (RESTAURANT_ID) REFERENCES FOOD_RESTAURANTS(RESTAURANT_ID),
    FOREIGN KEY (PARTNER_ID) REFERENCES FOOD_DELIVERY_PARTNERS(PARTNER_ID)
);